# Generated by Django 6.1.1 on 2026-09-24 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CitaPeluqueria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mascota', models.CharField(max_length=100)),
                ('raza', models.CharField(max_length=100)),
                ('tamano', models.CharField(choices=[('PEQUENO', 'Pequeño (1 - 10 kg)'), ('MEDIANO', 'Mediano (11 - 25 kg)'), ('GRANDE', 'Grande (Más de 25 kg)')], default='MEDIANO', max_length=10)),
                ('servicio', models.CharField(choices=[('CORTE', 'Corte de pelo y peinado'), ('BANO', 'Baño e higiene básica'), ('COMPLETO', 'Baño, Corte y Spa completo')], default='BANO', max_length=20)),
                ('fecha_hora', models.DateTimeField()),
                ('duracion_estimada_min', models.IntegerField(default=60)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
