# Generated by Django 6.1.1 on 2026-09-29 23:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peluqueria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citapeluqueria',
            options={'ordering': ['fecha_hora'], 'verbose_name': 'Cita de Peluquería', 'verbose_name_plural': 'Citas de Peluquería'},
        ),
        migrations.AddField(
            model_name='citapeluqueria',
            name='groomer',
            field=models.ForeignKey(blank=True, limit_choices_to={'id_rol__nombre_rol': 'groomer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_peluqueria', to=settings.AUTH_USER_MODEL, verbose_name='Groomer responsable'),
        ),
    ]
