# Generated by Django 6.1.1 on 2026-09-07 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dueno',
            fields=[
                ('id_dueno', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=20, unique=True)),
                ('direccion', models.CharField(max_length=255)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('es_recurrente', models.BooleanField(default=False)),
                ('numero_visitas', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Dueño',
                'verbose_name_plural': 'Dueños',
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id_mascota', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('especie', models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato'), ('otro', 'Otro')], max_length=20)),
                ('raza', models.CharField(blank=True, max_length=100)),
                ('tamano', models.CharField(blank=True, max_length=20)),
                ('sexo', models.CharField(blank=True, max_length=10)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('condicion_pelaje', models.CharField(blank=True, max_length=100)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('id_dueno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to='directorio.dueno')),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
            },
        ),
    ]
