# Generated by Django 6.1.1 on 2026-09-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='especie',
            field=models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato'), ('aves', 'Aves'), ('roedores', 'Roedores'), ('conejos', 'Conejos'), ('otro', 'Otro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=10),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='tamano',
            field=models.CharField(blank=True, choices=[('pequeno', 'Pequeño'), ('mediano', 'Mediano'), ('grande', 'Grande')], max_length=20),
        ),
    ]
