# Generated by Django 6.1.1 on 2026-09-23 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0002_alter_mascota_especie_alter_mascota_sexo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='codigo_mascota',
            field=models.CharField(blank=True, max_length=10, unique=True, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='color',
            field=models.CharField(blank=True, max_length=80, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='especie',
            field=models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato'), ('ave', 'Ave'), ('roedor', 'Roedor'), ('conejo', 'Conejo'), ('otro', 'Otro')], max_length=20),
        ),
    ]
