# Generated by Django 6.1.1 on 2026-09-25 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamiento', '0002_hu06_fix_cita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='hora_inicio',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='cita',
            name='motivo_cancelacion',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
